### ISSUE TITLE
Service crashes as soon as I log into the game

### ISSUE THREAD

**Issue by saix93** [BenJuan26/edca#1]
I'm trying to set this up and I'm having trouble making the service work.
I can configure, install and start it, but as soon as I open the game and choose a game mode, the service crashes.
I don't know if I can check any log somewhere to give you some more info.
My guess is that the game writes the Status.json file the moment you choose a game mode, and somehow that crashes the service.

Let me know if I can be of help.

Thank you!

**Comment by BenJuan26** [comment]
> My guess is that the game writes the Status.json file the moment you choose a game mode, and somehow that crashes the service.

That sounds like it must be the case. Log output from the service should go to Windows Event logs. They can be viewed with Event Viewer, in the Application category. I haven't changed the structs since before the Fleet Carrier update, so it's definitely possible some of the fields have been changed and the service is finding something it's not expecting. If you can find a crash log and post it here I can get to diagnosing. In the meantime I'll go through their Journal File Manual and see what might have changed.

**Comment by BenJuan26** [comment]
Oh, actually, a better option is probably to run `edca.exe debug`. That will run the service in the terminal instead of as a service, and it will be much easier to see what's happening and catch any crash logs.

**Comment by saix93** [comment]
I think you are absolutely right, it seems like the problem is the structs. This is the log i get in the console:
![image](https://user-images.githubusercontent.com/7765550/88725003-b6451100-d12b-11ea-9b90-0afce1c7b3db.png)

**Comment by BenJuan26** [comment]
Ah ok, I suspected it would be something like that. It looks like Cargo is a `float64`, not an `int64`. I'll verify that it's always a float, and in that case I'll update the struct. If it's not always the case, we're looking at some ugly Reflect behaviour 😕

**Comment by saix93** [comment]
Yes, that seems to be the problem.
Let's hope the variable stays the same :D
Thank you!

**Comment by BenJuan26** [comment]
I've bumped the `elite` version to `v0.1.2`, which has the fix. If you pull and run `go get` it should grab the change and you should be off to the races. Let me know if it works.

**Comment by saix93** [comment]
It looks like it works perfectly now 👍 
Thank you!
